### PR TITLE
UI of post feed enhanced

### LINKED ISSUE #8: UI enhancement of posts feed page and optimising UX off the app
Sir, The posts are overlapped and some of the icons are not in proper size which makes the UI of the page bad. @RitwikSingh28 kindly assign this issue of enhancing the UI to me.
WhatsApp Image 2023-10-12 at 00 42 36_86e76777

### PR DESCRIPTION
**Pull request by ShubhamTiwari55**
@RitwikSingh28 sir the issue #8 has been resolved. Changes like making icon size uniform, adding border radius to posts and making the overall page more readable by adding padding between elements have been done. Kindly review the changes 
WhatsApp Image 2023-10-13 at 11 15 27_6d5b80ca
The UI is now looking fine

### CODE REVIEW

**Comment by RitwikSingh28** [comment]
@ShubhamTiwari55 
May I know the reason for having closed this PR?

**Comment by ShubhamTiwari55** [comment]
@RitwikSingh28 Sir It was a mistake and also I had to update some more changes. I am reopening the pr. Kindly review them

**Review by RitwikSingh28 — CHANGES_REQUESTED** [review]
@ShubhamTiwari55 
Good work so far, although there are a few things that are wanting to change.

### Improvements

1. The `AppBar` background color looks a bit dull due to the shadow beneath it, so set its `elevation` to zero, and apply `Colors.transparent` in the `background-color` property
2. For the post, the image should only be rounded at the `top-left` and `top-right`, and the `Container` containing the like, comment, share feature should have a `bottom-left` and `bottom-right` rounded

**Comment by RitwikSingh28** [comment]
Also, use a `CircleAvatar` to encircle the display-pic of the user for a post. Would look better

**Comment by ShubhamTiwari55** [comment]
Okay sir I will update the required changes before 11.30 AM

**Comment by ShubhamTiwari55** [comment]
@RitwikSingh28 Sir the changes have been done. For the background color property, the previous color matched with the linear gradient itself and I think there is no need to apply gradient to app bar as there won't be any difference.
I had tried by apply gradient to appBar as well but it didn't look good so I just applied color to the app bar separately.
The UI will still look the same. If there are some other changes required Please let me know!
WhatsApp Image 2023-10-15 at 10 59 18_0d9cd160

**Review by RitwikSingh28 — APPROVED** [review]
Splendid work @ShubhamTiwari55 

No more changes required as of now. 
Merging into `main`

**Pull request merged**
