### PR TITLE
Fixed the pixel overflow 

### LINKED ISSUE #10: RenderOver Flow of Post Feed Card
Fix the render overflow of the sub-title section of post feed card

WhatsApp Image 2023-10-20 at 17 00 41_5deae47b

### PR DESCRIPTION
**Pull request by JayrajSinh16**
Fixed the pixel overflow in the Post Feed Card on the HomeScreen

### CODE REVIEW

**Comment by RitwikSingh28** [comment]
@JayrajSinh16 
Please provide the screenshot in the description of the PR.

**Comment by RitwikSingh28** [comment]
Also, please make sure that your remote repo is synced with this repo.
As the PR cannot be merged due to the resulting `merge conflicts`

**Comment by JayrajSinh16** [comment]
> @JayrajSinh16 Please provide the screenshot in the description of the PR.

WhatsApp Image 2023-10-21 at 13 22 56_3233ad1e

**Comment by JayrajSinh16** [comment]
@RitwikSingh28 
Resolved the Merge Conflicts

**Comment by RitwikSingh28** [comment]
@JayrajSinh16
You can reference the issue to get it resolved automatically by connecting it to this PR. For this, you need to add `Resolves #<issue_no>` or `Solves #<issue_no>`. 

In open source contributions, it is a good practice to always provide references to the issues that you aim to solve with a PR.

Also keep in mind to include screenshots in the PR description itself, from the next time onwards.

**Review by RitwikSingh28 — APPROVED** [review]
Great work @JayrajSinh16 ! Issue Resolved #10

**Pull request merged**
